version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/stack101-backend/zip/
    overwrite: yes

permissions:
  - objects: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user