version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/stack101-backend/zip/
    overwrite: yes

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 180
      runas: ec2-user