version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/stack101-backend/zip/
    overwrite: yes

permissions:
     - object: /
       pattern: "**"
       owner: ec2-user
       group: ec2-user
       
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 180
      runas: ec2-user